# Generated by Django 4.1.5 on 2023-01-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_reg_mess_restaurent',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reg_Mess_Restaurent',
        ),
        migrations.DeleteModel(
            name='Temp_Reg_Mess_Restaurent',
        ),
    ]
