# Generated by Django 4.1.5 on 2023-04-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_room_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporary',
            name='Advance',
            field=models.IntegerField(default=5000),
        ),
    ]
