# Generated by Django 4.1.5 on 2023-04-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_temporary_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Terms_and_conditions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='temporary',
            name='Terms_and_conditions',
            field=models.TextField(default=''),
        ),
    ]
