# Generated by Django 4.1.5 on 2023-04-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_room_terms_and_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Status',
            field=models.CharField(default='Rent', max_length=100),
        ),
    ]
