# Generated by Django 4.1.5 on 2023-04-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_room_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporary',
            name='start_date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
