# Generated by Django 4.1.5 on 2023-04-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_temporary_agreement_date_temporary_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporary',
            name='agreement_date',
        ),
        migrations.RemoveField(
            model_name='temporary',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='temporary',
            name='start_date',
        ),
        migrations.AddField(
            model_name='room',
            name='agreement_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='end_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='start_date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
