# Generated by Django 4.1.5 on 2023-04-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_remove_temporary_agreement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='agreement_date',
            field=models.CharField(default='10/10/2000', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='end_date',
            field=models.CharField(default='10/10/2000', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_date',
            field=models.CharField(default='10/10/2000', max_length=20),
        ),
    ]
