# Generated by Django 4.1.5 on 2023-02-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_premium_star_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='premium_star_date',
            new_name='premium_start_date',
        ),
    ]
