# Generated by Django 4.1.5 on 2023-02-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_premium_star_date_profile_premium_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='premium_start_date',
            field=models.CharField(blank=True, default='2022-03-01', max_length=20, null=True),
        ),
    ]
